const fs = require("fs").promises;
const path = require("path");

// Define the source and destination paths based on the original script
// NOTE: __dirname is the directory where this script resides.
const componentsDir = path.join(__dirname, "../src/components");
const outputFile = path.join(__dirname, "../src/data/generatedComponentCodes.js");

/**
 * Reads component files from subdirectories, generates React and Next.js code snippets,
 * and writes them to a structured JS file, along with logging skipped components.
 */
async function generateComponentCodes() {
  try {
    console.log(`Scanning directory: ${componentsDir}`);

    // Get all component directories and files
    const componentDirs = await fs.readdir(componentsDir, { withFileTypes: true });
    const componentCodes = {};
    const skippedComponents = []; // Array to track skipped components

    for (const dir of componentDirs) {
      if (dir.isDirectory()) {
        const componentName = dir.name;
        const componentPath = path.join(componentsDir, componentName);
        const files = await fs.readdir(componentPath);
        
        // Find the main component file (supports .jsx, .js, .tsx, excluding test files)
        const componentFile = files.find((file) => 
          (file.endsWith(".jsx") || file.endsWith(".js") || file.endsWith(".tsx")) && 
          !file.includes(".test.")
        );

        if (componentFile) {
          const displayName = componentName.replace(/([A-Z])/g, " $1").trim(); // e.g., "Basic Button"
          const filePath = path.join(componentPath, componentFile);
          let rawCode = await fs.readFile(filePath, "utf-8");

          // For the 'react' code, strip any leading "use client"; directive 
          // as it's often environment-specific.
          const reactCode = rawCode.replace(/^"use client";\s*/, '');

          // For the 'nextjs' code, ensure "use client" is present at the top.
          // This is a simple transformation, assuming the raw code is server component compatible
          // or is explicitly marked as client code.
          const nextjsCode = rawCode.startsWith('"use client";') ? rawCode : `"use client";\n${rawCode}`;

          componentCodes[displayName] = {
            react: reactCode,
            nextjs: nextjsCode,
          };
        } else {
          // Track components without a main file for detailed reporting
          skippedComponents.push({
            name: componentName,
            reason: `No main component file (.jsx, .js, or .tsx, non-test) found.`,
          });
        }
      }
    }

    // --- Part 1: Define and append getDefaultCode function ---
    const getDefaultCodeFunction = `
/**
 * Provides a fallback code snippet for a component name if the real code 
 * couldn't be loaded or is missing from the generated componentCodes map.
 * @param {string} componentName - The display name of the component (e.g., "Basic Button").
 * @returns {{react: string, nextjs: string}} - Object containing placeholder code.
 */
export const getDefaultCode = (componentName) => {
  // Convert display name (e.g., "Basic Button") to PascalCase (e.g., "BasicButton")
  const pascalCaseName = componentName.split(/\\s+/).map(word => word.charAt(0).toUpperCase() + word.slice(1)).join('');

  const fallbackReact = \`// React component code for \${componentName}
// This is a fallback placeholder. Please ensure the component file exists in the source directory.

import React from 'react';

const \${pascalCaseName} = () => {
  return (
    <div className="p-8 bg-neutral-800 rounded-lg shadow-xl m-4">
      <h3 className="text-white text-xl mb-4">\${componentName}</h3>
      <p className="text-neutral-300">
        Component implementation goes here...
      </p>
      <p className="text-sm text-yellow-400 mt-2">
        (Using fallback code because the source file was not found or was empty.)
      </p>
    </div>
  );
};

export default \${pascalCaseName};\`;

  return {
    react: fallbackReact,
    nextjs: \`// Next.js code will be available soon.
// \${componentName} is currently using the React fallback.\`,
  };
};
`;
    // --- End Part 1 ---

    // Write the generated componentCodes object followed by the function
    const outputContent = 
      `// This file is auto-generated by generateComponentCodes.js. Do not edit manually.

export const componentCodes = ${JSON.stringify(componentCodes, null, 2)};\n` +
      getDefaultCodeFunction;
      
    await fs.writeFile(outputFile, outputContent);
    console.log(`\n✅ Successfully generated component codes at ${outputFile}`);

    // --- Part 2: Reporting skipped components ---
    if (skippedComponents.length > 0) {
      console.warn("\n⚠️ Skipped the following component directories (missing main component file):");
      skippedComponents.forEach(s => {
        console.warn(`  - ${s.name}: ${s.reason}`);
      });
    } else {
      console.log("\n✅ No component directories were skipped.");
    }
    // --- End Part 2 ---

  } catch (error) {
    console.error("\n❌ Error generating component codes:", error.message);
    if (error.code === 'ENOENT') {
        console.error(`\n💡 Tip: Check if the components directory path is correct: ${componentsDir}`);
    }
  }
}

generateComponentCodes();
